project_id = "ljfubranindkcrniiobq"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false